namespace: tchecode
name: kvm_qemu
version: 0.1.0
readme: README.md
authors:
  - Lucas Lehnen <lucaslehnen@outlook.com>
description: Ansible Collection to install libvirt/qemu
license:
  - MIT
license_file: ''
tags:
  - libvirt
  - kvm
  - qemu
dependencies: {}
repository: https://github.com/lucaslehnen/tchecode.kvm_qemu
documentation: https://github.com/lucaslehnen/tchecode.kvm_qemu
homepage: https://github.com/lucaslehnen/tchecode.kvm_qemu
issues: https://github.com/lucaslehnen/tchecode.kvm_qemu/issues
build_ignore: []
