- name: "Uninstall libvirt packages"
  apt:
    pkg:
      - libvirt-daemon
      - qemu-kvm
      - bridge-utils
      - virtinst
      - libvirt-daemon-system
      - libguestfs-tools
      - libosinfo-bin
      - qemu-system
      - virt-manager
    state: absent
    purge: true
    autoclean: true

- name: "Disable 'vhost_net' kernel module"
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: vhost_net
    state: absent
  notify: reboot

- name: "Disable kvm_intel kernel module"
  file:
    path: /etc/modprobe.d/qemu-system-x86.conf
    state: absent
  notify: reboot
