- name: "Install libvirt packages"
  apt:
    pkg:
      - libvirt-daemon
      - qemu-kvm
      - bridge-utils
      - virtinst
      - libvirt-daemon-system
      - libguestfs-tools
      - libosinfo-bin
      - qemu-system
      - virt-manager
    update_cache: true
    state: present

- name: "Loading vhost_net kernel module"
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: vhost_net
    state: present
  notify: reboot

- name: "Loading kvm_intel kernel module"
  lineinfile:
    path: /etc/modprobe.d/qemu-system-x86.conf
    line: options kvm_intel nested=1
    state: present
    create: true
    mode: 0644
  notify: reboot

- name: "Checking the version"
  command: virsh version --daemon
  register: version
  changed_when: false

- name: "Show versions installed"
  debug:
    msg: "{{ version.stdout }}"
