- name: "list physical interfaces"
  shell: 
    cmd: find /sys/class/net -type l -execdir basename '{}' ';' | grep -v '^\(lo\|{{ bridge_network }}\)'
  register: physical_interface_cmd
  changed_when: false

- name: "Configuring the bridge network"
  template: 
    src: templates/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0440'
    backup: yes
  notify: reboot
  vars:
    physical_interface: "{{ physical_interface_cmd.stdout }}"

- name: "Configuring a bridge for QEmu"
  template:    
    src: "bridge.conf.j2"
    dest: "/etc/qemu/bridge.conf"
    mode: 0440
