- name: "Check if default pool exists "
  shell: 
    cmd: 'virsh pool-list --all | grep "default"'
  failed_when: "check_pool_default.rc == 2"
  changed_when: false
  register: check_pool_default

- name: "Creating the default pool"
  shell: 
    cmd: 'virsh pool-define-as default dir - - - - /var/lib/libvirt/images'    
  when: check_pool_default.stdout.find('default') < 0

- name: "Initializing the default pool"
  shell: 
    cmd: 'virsh pool-start default'    
  when: check_pool_default.stdout.find('inativo') >= 0
  